language: java

notifications:
  email:
    recipients:
      - brent.smith@redspace.com
      - mark.mckenna@redspace.com
    on_success: change
    on_failure: change
  slack: redspace:zl6TpOjRxLeLRqV7I6bNecR5
